---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: yc-network-hdd #change storage class for advanced
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-conf
  namespace: nextcloud
  labels:
    app: nextcloud
data:
  # db params
  db_name: nextcloud # database name
  db_address: '10.129.0.30' # address, ip or fqdn
  # redis params
  redis_host: '10.129.0.11' # change for advanced
  redis_host_port: '6379' # default port
  # s3 params
  object_host: 'https://storage.yandexcloud.net' # change
  object_region: ru-central1
  object_port: '443'
  # app params
  nextcloud_data: /var/www/html/data
  nextcloud_url: http://nextcloud.ghostklart.com
  nextcloud_upload: 12G
  nextcloud_file_upload: "20"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-app
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: nextcloud-storage
      containers:
        - name: nextcloud
          image: nextcloud:fpm
          env:
          # system
          - name: TZ
            value: Europe/Moscow
          # app settings
          - name: NEXTCLOUD_URL
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: nextcloud_url
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: nc_user
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: nc_password
          - name: NEXTCLOUD_DATA_DIR
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: nextcloud_data
          - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: nextcloud_upload
          - name: NEXTCLOUD_MAX_FILE_UPLOADS
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: nextcloud_file_upload
          # database settings
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: db_name
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: mysql_password
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: db_address
          # s3 backend settings
          - name: OBJECTSTORE_S3_HOST
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: object_host
          - name: OBJECTSTORE_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: object_bucket
          - name: OBJECTSTORE_S3_KEY
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: object_ak
          - name: OBJECTSTORE_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: object_sk
          - name: OBJECTSTORE_S3_REGION
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: object_region
          - name: OBJECTSTORE_S3_PORT
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: object_port
          - name: OBJECTSTORE_S3_USEPATH_STYLE
            value: 'true'
          # redis settings
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: redis_host
          - name: REDIS_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: nextcloud-conf
                key: redis_host_port
          - name: REDIS_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: redis_password
          # storage
          volumeMounts:
          - name: app-storage
            mountPath: /var/www/html
          resources:
            requests:
              cpu: '4'
              memory: '8Gi'
            limits:
              cpu: '8'
              memory: '16Gi'
          ports:
          - name: nc-http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-lb
  namespace: nextcloud
spec:
  ports:
    - name: nc-http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nextcloud
  type: LoadBalancer